export const Dashboard_Sidebar_Links=[
    {
        key:"dashboard",
        label:"Dashboard",
        path:"/dashboard",
        icon:""
    },
    {
        key:"products",
        label:"Products",
        path:"/products",
        icon:""
    },
    {
        key:"customers",
        label:"Customers",
        path:"/customers",
        icon:""
    },
    {
        key:"orders",
        label:"Orders",
        path:"/orders",
        icon:""
    }
]
export const Sidebar_Bottom_Links=[ {
    key:"login",
    label:"Login",
    path:"/login",
    icon:""
},
{
    key:"logout",
    label:"Logout",
    path:"/logout",
    icon:""
}]